name: mercado_pago
description: Mercado Pago Library - A flutter plugin to integrate MercadoPago into flutter app
version: 1.0.5
homepage: https://github.com/briansalvattore/mercado_pago_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  test: 1.14.2

flutter: